// ── DOM 元素引用 ──────────────────────────────────────────────────
// 集中管理所有的 DOM 元素引用，避免在业务逻辑中直接查询 DOM
export const dom = {
  editorContainer: document.getElementById('editor-container'),
  preview: document.getElementById('mermaid-preview'),
  previewViewport: document.getElementById('preview-viewport'),
  zoomLabel: document.getElementById('zoom-label'),
  btnZoomIn: document.getElementById('btn-zoom-in'),
  btnZoomOut: document.getElementById('btn-zoom-out'),
  btnZoomReset: document.getElementById('btn-zoom-reset'),
  themeSelect: document.getElementById('theme-select'),
  handDrawnBtn: document.getElementById('hand-drawn-btn'),
  uiThemeToggle: document.getElementById('ui-theme-toggle'),
  btnCopyPng: document.getElementById('btn-copy-png'),
  btnDownloadSvg: document.getElementById('btn-download-svg'),
  btnDownloadPng: document.getElementById('btn-download-png'),
  btnShare: document.getElementById('btn-share'),
  btnEmbedCode: document.getElementById('btn-embed-code'),
  menubar: document.getElementById('menubar'),
  btnHelp: document.getElementById('btn-help'),
  divider: document.getElementById('divider'),
  toast: document.getElementById('toast'),
  editorStatus: document.getElementById('editor-status'),
  renderStatus: document.getElementById('render-status'),
  iconSun: document.getElementById('icon-sun'),
  iconMoon: document.getElementById('icon-moon'),
  iconSunQuick: document.getElementById('icon-sun-quick'),
  iconMoonQuick: document.getElementById('icon-moon-quick'),
  uiThemeToggleQuick: document.getElementById('ui-theme-toggle-quick'),
  handDrawnToggleQuick: document.getElementById('hand-drawn-toggle-quick'),
  helpModal: document.getElementById('help-modal'),
  modalClose: document.getElementById('modal-close'),
  modalOk: document.getElementById('modal-ok'),
  btnRestartTour: document.getElementById('btn-restart-tour'),
  tourOverlay: document.getElementById('tour-overlay'),
  tourHighlight: document.getElementById('tour-highlight'),
  tourTooltip: document.getElementById('tour-tooltip'),
  tourCurtainTop: document.getElementById('tour-curtain-top'),
  tourCurtainBottom: document.getElementById('tour-curtain-bottom'),
  tourCurtainLeft: document.getElementById('tour-curtain-left'),
  tourCurtainRight: document.getElementById('tour-curtain-right'),
  tourStepEl: document.getElementById('tour-step'),
  tourTitleEl: document.getElementById('tour-title'),
  tourBodyEl: document.getElementById('tour-body'),
  tourDotsEl: document.getElementById('tour-dots'),
  tourSkip: document.getElementById('tour-skip'),
  tourNext: document.getElementById('tour-next'),
};
